### ISSUE TITLE
Request for urgent support

### ISSUE THREAD

**Issue by ghost** [mallorym/cucumber-protractor-harness#10]

**Comment by Mustafa0691** [comment]
https://github.com/mallorym/cucumber-protractor-harness/commit/7ca0414d4b6423fa150c069952397104fca54cea#r36566858

**Comment by Mustafa0691** [comment]
defineSupportCode(function({Given, When, Then}) {


here I am getting the error in step -def file

**Comment by Mustafa0691** [comment]
Resolved
