### ISSUE TITLE
The Given and the When line go green before WebDriver has even landed on the page

### ISSUE THREAD

**Issue by ph-ms** [mallorym/cucumber-protractor-harness#2]
Is that right?

**Comment by thangakumard** [comment]
I too have the same issue. Cucumber steps execution is not sync with browser action. Before browser perform an action, all my cucumber steps got passed ! Please share if you solved this issue

**Comment by mallorym** [comment]
Hey guys! I haven't had the chance to look into this yet, but I will try to do that this week. I haven't run into that issue with this project. It may be time to update some modules.

**Comment by mallorym** [comment]
@ph-ms @TK23061984 could you pull the latest and try again? should be working for you. Note I updated dependency versions.

**Comment by mallorym** [comment]
Closing issue.
